name: data
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - name: Check out repo
        uses: actions/checkout@v2 
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://www.shazam.com/shazam/v3/en-US/US/web/-/tracks/world-chart-world?pageSize=200&startFrom=0
          downloaded_filename: world-top200.json
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://www.shazam.com/shazam/v3/en-US/US/web/-/tracks/ip-country-chart-US?pageSize=200&startFrom=0
          downloaded_filename: usa-US-top200.json
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://www.shazam.com/shazam/v3/en-US/US/web/-/tracks/ip-city-chart-5105496?pageSize=200&startFrom=0
          downloaded_filename: trenton-5105496-top200.json
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://www.shazam.com/shazam/v3/en-US/US/web/-/tracks/ip-country-chart-IN?pageSize=200&startFrom=0
          downloaded_filename: india-IN-top200.json
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://www.shazam.com/shazam/v3/en-US/US/web/-/tracks/risers-country-chart-US?pageSize=20&startFrom=0
          downloaded_filename: usa-US-rising.json
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://www.shazam.com/shazam/v3/en-US/US/web/-/tracks/risers-country-chart-IN?pageSize=20&startFrom=0
          downloaded_filename: india-IN-rising.json
