name: data
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - name: Check out repo
        uses: actions/checkout@v4 
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://www.shazam.com/services/charts/csv/top-200/world
          downloaded_filename: world-top200.csv
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://www.shazam.com/services/charts/csv/top-200/united-states
          downloaded_filename: usa-top200.csv
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://www.shazam.com/services/charts/csv/top-50/united-states/newark
          downloaded_filename: newark-top50.csv
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://www.shazam.com/services/charts/csv/top-200/india
          downloaded_filename: india-top200.csv
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://www.shazam.com/services/charts/csv/discovery/united-states
          downloaded_filename: usa-discovery.json
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://www.shazam.com/services/charts/csv/discovery/india
          downloaded_filename: india-discovery.json
